
import __ASTRO_IMAGE_IMPORT_Z1EeNDD from "./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F2.pinterest-clone.mdx";
import __ASTRO_IMAGE_IMPORT_bT9Hd from "./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F1.finpos-field-visit.mdx";
import __ASTRO_IMAGE_IMPORT_Zbvkdo from "./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F3.sarpras-sebelas.mdx";
import __ASTRO_IMAGE_IMPORT_Z1DGda1 from "./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F4.rock-paper-scissor-classification.mdx";
import __ASTRO_IMAGE_IMPORT_Z1422Ew from "./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F5.competitive-programmings.mdx";
import __ASTRO_IMAGE_IMPORT_29VB7q from "./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F6.csr-goverment.mdx";
import __ASTRO_IMAGE_IMPORT_dL9HH from "./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F7.HF-Store.mdx";
import __ASTRO_IMAGE_IMPORT_2dq1hE from "./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F9.simple-finance-apps.mdx";
import __ASTRO_IMAGE_IMPORT_Z2wCXAE from "./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F8.pelita-taras.mdx";
export default new Map([["./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F2.pinterest-clone.mdx", __ASTRO_IMAGE_IMPORT_Z1EeNDD], ["./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F1.finpos-field-visit.mdx", __ASTRO_IMAGE_IMPORT_bT9Hd], ["./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F3.sarpras-sebelas.mdx", __ASTRO_IMAGE_IMPORT_Zbvkdo], ["./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F4.rock-paper-scissor-classification.mdx", __ASTRO_IMAGE_IMPORT_Z1DGda1], ["./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F5.competitive-programmings.mdx", __ASTRO_IMAGE_IMPORT_Z1422Ew], ["./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F6.csr-goverment.mdx", __ASTRO_IMAGE_IMPORT_29VB7q], ["./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F7.HF-Store.mdx", __ASTRO_IMAGE_IMPORT_dL9HH], ["./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F9.simple-finance-apps.mdx", __ASTRO_IMAGE_IMPORT_2dq1hE], ["./images/competitive-programmings/cover.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F8.pelita-taras.mdx", __ASTRO_IMAGE_IMPORT_Z2wCXAE]]);
		